name: Continuous Integration
on:
  pull_request:
    branches: ["main", "dev"]

jobs:
  Continuous Integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22.x
      - name: install, build and test
        run: |
          npm install
          npm install -g pnpm
          pnpm install
          pnpm run build
          pnpm run test
